colour = input("enter a colour : ")
plural_noun = input("enter a plural_noun : ")
celebrity = input("enter a celebrity : ")
print("roses are " + colour)
print(plural_noun + " are blue")
print("i love " + celebrity)
